### ISSUE TITLE
Wrong dependency on PK_WRITE for RSA_C when PSA_CRYPTO_C is enabled

### ISSUE THREAD

**Issue by joerchan** [Mbed-TLS/mbedtls#7126]
### Summary
I am currently integrating the nRF Connect SDK with Mbed TLS 3.2.1 and TF-M 1.7.0 and I have run into a new build warning coming from new dependencies introduced in MBedTLS 3.2.1.

The warning:
```
pk_wrap.c: In function ‘mbedtls_pk_psa_rsa_sign_ext’:
pk_wrap.c:288:15: warning: implicit declaration of function ‘mbedtls_pk_write_key_der’;
 did you mean ‘mbedtls_ecp_write_key’? [-Wimplicit-function-declaration]
  288 |     key_len = mbedtls_pk_write_key_der( &key, buf, sizeof( buf ) );
      |               ^~~~~~~~~~~~~~~~~~~~~~~~
      |               mbedtls_ecp_write_key
```
The reason for the warning is that MBEDTLS_PK_WRITE_C is not enabled, while MBEDTLS_RSA_C and MBEDTLS_PSA_CRYPTO_C is enabled.
This causes the definition of `mbedtls_pk_write_key_der` to be compiled out of the header file.
In order to fix this, I need to enable PK_WRITE_C and then additional dependencies required by that.

From looking at other functions that call `mbedtls_pk_write_key_der` this is guarded by the check for MBEDTLS_USE_PSA_CRYPTO instead. An example of this is is `rsa_decrypt_wrap` using `mbedtls_pk_write_key_der` in the same file, and `ecdsa_sign_wrap`.

Instead of enabling MBEDTLS_PK_WRITE_C and it's chain of dependencies I believe this is just a mix up of the two very similar symbols, and the fix for this warning is this:
```
iff --git a/library/pk_wrap.c b/library/pk_wrap.c
index c6892ad43..bc6b5b5a5 100644
--- a/library/pk_wrap.c
+++ b/library/pk_wrap.c
@@ -261,7 +261,7 @@ static int rsa_verify_wrap( void *ctx, mbedtls_md_type_t md_alg,
 }
 #endif
 
-#if defined(MBEDTLS_PSA_CRYPTO_C)
+#if defined(MBEDTLS_USE_PSA_CRYPTO)
 int  mbedtls_pk_psa_rsa_sign_ext( psa_algorithm_t alg,
                                   mbedtls_rsa_context *rsa_ctx,
                                   const unsigned char *hash, size_t hash_len,
```

Since the 3.2.1 tag in the development branch this has been further addressed by actually auto-enabling these dependencies.
By the following code:
```
/* The PK wrappers need pk_write functions to format RSA key objects
 * when they are dispatching to the PSA API. This happens under USE_PSA_CRYPTO,
 * and also even without USE_PSA_CRYPTO for mbedtls_pk_sign_ext().
 * PSA crypto also needs pk_write to export RSA keys (otherwise the build
 * goes through but psa_export_key() and psa_export_public_key() fail on
 * RSA keys), and pk_parse to work with RSA keys in almost any way.
 */
#if defined(MBEDTLS_PSA_CRYPTO_C) && defined(MBEDTLS_RSA_C)
#define MBEDTLS_PK_C#define MBEDTLS_PK_WRITE_C
#define MBEDTLS_PK_PARSE_C
#endif

/* Under MBEDTLS_USE_PSA_CRYPTO, the pk module needs pk_write functions* to pass ECC keys to PSA. */
#if defined(MBEDTLS_PK_C) &&                                    \
    defined(MBEDTLS_USE_PSA_CRYPTO) && defined(MBEDTLS_ECP_C)
#define MBEDTLS_PK_WRITE_C
#endif
```

This means that the build warning no longer shows up, but the dependencies are unnecessary in my opinion.
I believe this should also be updated to use `MBEDTLS_USE_PSA_CRYPTO` also instead of `MBEDTLS_PSA_CRYPTO_C`.

In addition the reason for the build warning is that the function prototype is compiled out, but the implementation itself is not.
The function implementation should also be compiled out when not enabled to ensure that MBed TLS save code space and do not include features that are not enabled by accident in the build.

### System information

Mbed TLS version (number or commit id):  3.2.1 (+ TF-M 1.7.0 patches)
Operating system and version: 
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
Additional environment information: 

### Expected behavior
No build warning.
`mbedtls_pk_write_key_der` only being included in the build when MBEDTLS_PK_WRITE_C is enabled.
Not needing MBEDTLS_PK_WRITE_C when MBEDTLS_PSA_CRYPTO_C is enabled, but not using MBEDTLS_PSA_CRYPTO_C.

### Actual behavior
Build warning and function is still compiled.

### Steps to reproduce
On 3.2.1 tag:
```
./scripts/config.py crypto
make clean
make -j32 lib
```

### Additional information
Related PR: https://github.com/Mbed-TLS/mbedtls/pull/6389
Related issue (and comment): https://github.com/Mbed-TLS/mbedtls/issues/7055#issuecomment-1423981579

**Comment by mpg** [comment]
Hi Joakim, and thanks for your report! I think there are several distinct but related points here. As you noted, the build warning as been fixed in the meantime, so I think the two remaining points are:

1. `mbedtls_pk_psa_rsa_sign_ext()` is guarded by `MBEDTLS_PSA_CRYPTO_C` while other similar functions are guarded by `MBEDTLS_USE_PSA_CRYPTO`. I agree it looks suspicious, but actually I think it's intentional: it's not just this function, the public function `mbedtls_pk_sign_ext()` is using the same guard (both in the header an C files), and the comment in `build_info.h` is consistent with that. Now, just because it was intentional doesn't mean it's right. I seem to remember guarding `mbedtls_pk_sign_ext()` that way had something to do with the fact that TLS 1.3 needed it, and that TLS 1.3 only requires `MBEDTLS_PSA_CRYPTO_C` not `MBEDTLS_USE_PSA_CRYPTO`. I don't remember the full story, so I'll do some digging and come back to you.
2. You'd like to be able to exclude `MBEDTLS_PK_WRITE_C` from the build when RSA is supported and `MBEDTLS_PSA_CRYPTO_C` is defined but `MBEDTLS_USE_PSA_CRYPTO` is not. This depends on the previous point, but unfortunately, I don't think that boils down to just the previous point: PK write is also used in `psa_crypto_rsa.c`. So, this might not be possible at the moment. Again, I'll investigate further and come back to you.

A middle-ground might be to define a subset of PK write and auto-enable only that subset when needed for RSA, but I'm not sure that would really be better than what the linker's garbage collector can do.

**Comment by joerchan** [comment]
For 2.), atleast for us at MBed TLS 3.2.1 our CI system is happy. Everything compiles. We're still dealing with some issues during CI run, so maybe there is still something there. But atleast for me this looks very much like the correct solution.
Changing the dependencies had problems for me, because I had to go and get subsequent dependencies, and this quickly snowballed out of control. I didn't get to a point where it all compiled.

**Comment by gilles-peskine-arm** [comment]
The bug about a _missing_ dependency on `MBEDTLS_PK_WRITE_C` was previously reported in https://github.com/Mbed-TLS/mbedtls/issues/6408 and fixed in Mbed TLS 3.3.0 (the patch is in https://github.com/Mbed-TLS/mbedtls/pull/6410).

The dependency on `mbedtls_pk_psa_rsa_sign_ext` is correct: as Manuel mentioned, that function is used in TLS 1.3 code that does not depend on `MBEDTLS_USE_PSA_CRYPTO`.

With respect to the definition and declaration of `mbedtls_pk_psa_rsa_sign_ext`: both are guarded by `defined(MBEDTLS_PSA_CRYPTO_C) && defined(MBEDTLS_RSA_C)` (with different nesting of `#if` statements, but ending up with the same condition).

So I'm not seeing any bug here.

Removing the requirement for PK_PARSE and PK_WRITE when PSA uses RSA keys is something we want to do in the long term, but it requires an independent implementation of some ASN.1 parsing and formatting, so it's not going to happen soon.

**Comment by mpg** [comment]
> So I'm not seeing any bug here.
> 
> Removing the requirement for PK_PARSE and PK_WRITE when PSA uses RSA keys is something we want to do in the long term, but it requires an independent implementation of some ASN.1 parsing and formatting, so it's not going to happen soon.

I was coming to the same conclusion: not seeing any bug left (the part that was a bug, ie the compilation warning/error, has been fixed already), and I think the rest is an enhancement request that we're not ready to address in the short term.

**Comment by mpg** [comment]
While I still can't see a bug here, there's definitely room for improvement, so I'm relabeling as "enhancement".

**Comment by mpg** [comment]
Regarding the first point identified in https://github.com/Mbed-TLS/mbedtls/issues/7126#issuecomment-1436762669 I think we can and should make `mbedtls_pk_sign_ext()` always available (ie stop depending on `MBEDTLS_PSA_CRYPTO_C`), by providing a legacy implementation using `rsa.h` when PSA isn't available, and using either the PSA or the legacy based on `USE_PSA_CRYPTO`. That way, it will not only address the point made here, but also improve uniformity in the PK module

Originally when we added this function we thought it would be easier to only provide a PSA implementation, but it turns out the lack of uniformity is making things more complicated (see this discussion, but also [here](https://github.com/Mbed-TLS/mbedtls/pull/7514/files#diff-a937102a7320aa733cea041bdf41c917bfbaded31036b2c2907cff478022b0a6R238) for example), so it's better for this function to behave like the others (and in particular like its symmetric `mbedtls_pk_verify_ext()`: be always defined, and obey `USE_PSA_CRYPTO`.

**Comment by mpg** [comment]
Regarding the second point, `psa_crypto_rsa.c` is using 4 functions from PK write/parse: `mbedtls_pk_parse_key()`, `mbedtls_pk_parse_public_key()`, `mbedtls_pk_write_key_der()` and `mbedtls_pk_write_pubkey()` - which makes complete sense because it needs to import/export private/public keys.

What makes perhaps less sense is that it needs to drag in the whole of PK to do that. Contrast with `psa_crypto_ecp.c` which takes is writing/parsing functions from `ecp.c`, not `pkxxx.c`.

I'm starting to think that the code for parsing & writing RSA private/public keys in the basic PKCS1 format belongs in `rsa.c`, not `pkparse.c` + `pkwrite.c`. PK parse/write should be about parsing extended formats (PKCS8, PKCS12, PEM, encrypted) by building of top of the basic format for each key type that would be provided by the implementation of each key type - so in that case `rsa.c`.

This would be a simple refactoring: move `pk_parse_key_pkcs1_der()`, `pk_get_rsapubkey()`, `pk_write_rsa_pubkey()` and the RSA part of `mbedtls_pk_write_key_der()` to `rsa.c`, with appropriate names, declared in `rsa.h` (or a new header `library/rsa_internal.h` if we don't want to extend the legacy API at this point), and then use those functions both in PK write/parse and in `psa_crypto_rsa.c`.

That way `psa_crypto_rsa.c` only depends on `rsa.c` (and PK parse/write keeps depending on `rsa.c` for RSA support as usual).

Wdyt?

Cc @gilles-peskine-arm

**Comment by joerchan** [comment]
@mpg Thanks for coming back to this.

I still consider it a bug if you get the function compiled in, but not the function prototype.
The function prototype should not have been compiled in in that case, or an invalid configuration should have been warned about.

I can't speak on all of your points here, I'm mostly trying to satisfy various build requirements coming from our protocol users of crypto.
We would prefer that everything is using PSA and not extend on the legacy API. The complexity is too large with developing on two crypto APIs (legacy and PSA) for a diverse set of use-cases.

**Comment by mpg** [comment]
> We would prefer that everything is using PSA and not extend on the legacy API. The complexity is too large with developing on two crypto APIs (legacy and PSA) for a diverse set of use-cases

I too would prefer using PSA only everywhere, and not having to deal with the complexity of maintaining two crypto APIs, believe me I'm very well aware of how much work it is! That's actually what motivated the initial decision to only provide a PSA-based implementation `mbedtls_pk_verify_ext()` which resulted in in depending on `PSA_CRYPTO_C` which is now causing issues.

PK was initially an abstraction layer so you can use the same set of functions with either RSA and ECC keys. Now it doubles as an abstraction layer so you can use the same set of functions and under the hood either the legacy interface is use, or PSA Crypto (with support for drivers) depending on `USE_PSA_CRYPTO`.

Abstraction layers work best when they present a uniform set of features to users. Having one function defined or not depending on one of the things we're trying to abstract (whether PSA is present or not) is not great. Lack of uniformity in how things work (PK functions for crypto operations obey `USE_PSA_CRYPTO` _except_ this one) is not great either.

In that case I think providing a legacy implementation of this function is the lesser of two evils, as it results in a better, more uniform abstraction.

**Comment by gilles-peskine-arm** [comment]
> the code for parsing & writing RSA private/public keys in the basic PKCS1 format belongs in rsa.c, not pkparse.c + pkwrite.c

When I first wrote the PSA code, I couldn't change existing files, so PSA had to call whatever APIs existed. Nowadays we can extend legacy modules for the sake of PSA.

It could make sense that RSA/ECP/ECDSA would work with bignums and pk would work with byte strings. However, this distinction is not always made: `ecp.h` and `ecdsa.h` have some byte-string interfaces (read/write point, read/write signature). Since there's already no consistent boundary, we can shift that boundary.

Historically I wanted to avoid making PSA crypto depend on ASN.1. Currently its dependencies are indirect: RSA PKCS#1v1.5 signature (via `rsa.c`), RSA key formats (via `pkparse.c` and `pkwrite.c`). I'm not sure if it makes sense to do RSA key parsing and formatting without using the generic ASN.1 interface. If not, then we should just embrace the fact that ASN.1 is going to stay firmly rooted in the crypto library and can't move to X.509. (But no, there will not be a PSA ASN.1 interface. This will remain an mbedtls API, even if it's in the psa-crypto repository.)

**Comment by mpg** [comment]
I think this issue have been resolved by #7930 (thank you @tomi-font!) and #8740.

We now have a test component that builds with `PSA_CRYPTO_C` and `RSA_C` enabled but `PK_WRITE_C` disabled. (Currently `common_test_psa_crypto_config_accel_ecc_some_curves`, and [soon another one disabling just PK parse/write](https://github.com/Mbed-TLS/mbedtls/pull/8774/files#diff-e683396c93d3af1ea2db5a3d94788da3916ed084f3eb8be5e5f7c0e429badf39R1534).)

So, I'm closing this issue. Thanks again for suggesting this improvement.
